spring:
  datasource:
    url: jdbc:mysql://192.168.14.128:3306/gym_management_system
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false #关闭缓存


#server:
#  port: 8888

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    #配置日志
    map-underscore-to-camel-case: true #驼峰命名规范
    #实体类别名包路径
  type-aliases-package: com.milotnt.pojo